name: Enforce PR labels

permissions:
  contents: read

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
  workflow_dispatch: # manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  enforce-label:
    runs-on: ubuntu-24.04
    steps:
    - uses: yogevbd/enforce-label-action@a3c219da6b8fa73f6ba62b68ff09c469b3a1c024
      with:
        BANNED_LABELS: "Input: Staff,Input: Author,Needs Announcement,Needs Changelog,Needs Documentation,Stale"
